const puppeteer = require('puppeteer');
const fetch = require('node-fetch');

async function generateTextWithChat(prompt, openaiApiKey) {
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${openaiApiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: "gpt-3.5-turbo",
      messages: [{ role: "user", content: prompt }]
    })
  });

  if (!response.ok) {
    console.error(`Error making request: ${response.statusText}`);
    return 'Error: Failed to generate content';
  }

  const data = await response.json();
  return data.choices[0].message.content.trim();
}

async function registerAndPublishToWordPress(pageUrl, anchorText, language, openaiApiKey) {
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();
  const fakeEmail = `user${new Date().getTime()}@example.com`;

  await page.goto('https://wordpress.com/start/user-social', { waitUntil: 'networkidle2' });
  
  // Убедитесь, что кнопка для продолжения через email загрузилась и кликните по ней
  await page.waitForSelector('.social-buttons__button', {visible: true, timeout: 30000});
  await page.click('.social-buttons__button');

  // Дождитесь появления поля ввода и введите email
  await page.waitForSelector('.form-text-input.signup-form__passwordless-email', {visible: true, timeout: 30000});
  await page.type('.form-text-input.signup-form__passwordless-email', fakeEmail);
  await page.click('.button.is-primary');

  // Ожидайте навигации после ввода email
  await page.waitForNavigation({ waitUntil: 'networkidle2' });
  await page.type('input#search-component-search-1', 'mytestsite');
  await page.click('.domain-suggestion.card.is-compact');
  await page.click('.button.plan-features-2023-grid__actions-button.is-free-plan');
  await page.click('.button.navigation-link.step-container__navigation-link');

  const title = await generateTextWithChat(`Generate a title for an article about this link: ${pageUrl}`, openaiApiKey);
  const content = await generateTextWithChat(`Create content in ${language} based on this link: ${pageUrl}. Include the anchor text "${anchorText}" as a link.`, openaiApiKey);

  await page.goto(`https://wordpress.com/post/mytestsite.wordpress.com`);
  await page.type('textarea.post-title__input', title);
  await page.type('.mce-content-body', content);
  await page.click('.editor-post-publish-panel__toggle');
  await page.click('.editor-post-publish-button__button');

  const url = await page.evaluate(() => location.href);
  await browser.close();
  return { publishedUrl: url, title, author: 'AutoGenerated', network: 'WordPress' };
}

module.exports = {
  publish: registerAndPublishToWordPress
};
